---
abstract: 'Client API to the service of Smartsheet.com'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-SmartSheet
requires:
  Carp: 0
  Data::Dumper: 0
  JSON: 0
  LWP::UserAgent: 0
  Moo: 0
  MooX::late: 0
resources:
  homepage: http://smartsheet.com/
  repository: https://github.com/szabgab/WWW-SmartSheet.git
version: 0.01
